# Identificação do Projeto no SonarCloud
sonar.organization=gabriel-bebe
sonar.projectKey=Gabriel24701_dev-life-api

# Onde está o código que deve ser analisado? (Apenas a API em Python por enquanto)
sonar.sources=.
sonar.exclusions=tests/**, dev-life-web/**, venv/**, .venv/**, __pycache__/**

# Onde estão os testes?
sonar.tests=tests/

# Configurações do Python
sonar.language=py
sonar.python.version=3.11