sonar.organization=gabriel-bebe
sonar.projectKey=Gabriel24701_dev-life-api

sonar.sources=.
sonar.exclusions=tests/**, dev-life-web/**, venv/**, .venv/**, __pycache__/**

sonar.tests=tests/

sonar.language=py
sonar.python.version=3.11